Extra testing for various type of EOL

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -4,19 +4,25 @@ CXXFLAGS=-O2
 
 all:$(PROG)
 
-check:$(PROG) ../test/sqlite3.c
-	for p in $(PROG) ; do \
-		printf "$$p: " 1>&2 ;\
-		./$$p ../test/sqlite3.c > $$p.data ; \
-		cmp $$p.data ref.data || echo "$$p invalid" ; \
+check:$(PROG) ../test/sqlite3.c ../test/sqlite3_r.c ../test/sqlite3_rn.c
+	for t in ../test/sqlite3.c ../test/sqlite3_r.c ../test/sqlite3_rn.c; do \
+		echo "= $$t" ;\
+		for p in $(PROG) ; do \
+			printf "$$p: " 1>&2 ;\
+			./$$p $$t > $$p.`basename $$t .c`.data ; \
+			cmp $$p.`basename $$t .c`.data ref.`basename $$t .c`.data || echo "$$p invalid" ; \
+		done \
 	done
 
 perf: $(PROG)
-	for p in $(PROG) ; do \
-		printf "$$p: " 1>&2 ;\
-		for _ in `seq 100` ; do \
-		  ./$$p ../test/sqlite3.c > /dev/null ;\
-		done 2>&1 | awk 'BEGIN { s=0; } { s+=$$1; } END { print(s/NR); }' ; \
+	for t in ../test/sqlite3.c ../test/sqlite3_r.c ../test/sqlite3_rn.c; do \
+		echo "= $$t" ;\
+		for p in $(PROG) ; do \
+			printf "$$p: " 1>&2 ;\
+			for _ in `seq 100` ; do \
+			  ./$$p ../test/sqlite3.c > /dev/null ;\
+			done 2>&1 | awk 'BEGIN { s=0; } { s+=$$1; } END { print(s/NR); }' ; \
+		done \
 	done
 
 clean:
